"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import type { ChainEntry, EntryWithBody, ViewJson } from "@/lib/types";

interface Props {
  slug: string;
  view: ViewJson;
  cached: boolean;
  generatedAt: string;
  costUsd: number;
  /** Map of entry id -> entry+body for resolving referenced ids. */
  bodies: Record<string, EntryWithBody>;
  entriesById: Record<string, ChainEntry>;
  /** Forward a "Reply" click to PageView so it opens the composer. */
  onReply: (entry: ChainEntry) => void;
}

/**
 * Renders an LLM-generated view_json through a fixed component palette.
 *
 * The palette is intentionally small and has NO raw-HTML escape hatch:
 *   <Group> | <SectionSummary> | <Callout> | <FilterChip> | <EntryRef>
 *
 * Posters' bodies (rendered inside <EntryRef>) go through react-markdown with
 * <script>/<iframe>/<style>/<img> stripped. The LLM's text fields are rendered
 * as PLAIN TEXT (no markdown) so even if a prompt-injection slipped past
 * schema validation, it can't emit clickable links or images.
 */
export function AiView({
  slug,
  view,
  cached,
  generatedAt,
  costUsd,
  bodies,
  entriesById,
  onReply,
}: Props) {
  return (
    <div className="space-y-8">
      {view.section_summaries.length > 0 && (
        <section className="rounded-lg border border-zinc-200 bg-white p-5">
          <ul className="space-y-3">
            {view.section_summaries.map((s, i) => (
              <li key={i}>
                <h3 className="text-sm font-semibold text-zinc-900">
                  {s.label}
                </h3>
                <p className="text-sm text-zinc-700 mt-1 leading-relaxed">
                  {s.text}
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}

      {view.callouts.length > 0 && (
        <section className="space-y-2">
          {view.callouts.map((c, i) => (
            <Callout
              key={i}
              tone={c.tone}
              text={c.text}
              relatedEntryIds={c.related_entry_ids}
            />
          ))}
        </section>
      )}

      {view.suggested_filters.length > 0 && (
        <section>
          <div className="text-xs uppercase tracking-wide text-zinc-500 mb-2">
            Try
          </div>
          <ul className="flex flex-wrap gap-2">
            {view.suggested_filters.map((f, i) => (
              <li key={i}>
                <span
                  className="inline-block rounded-full border border-zinc-300 bg-white px-3 py-1 text-sm text-zinc-700 hover:bg-zinc-50"
                  title={f.natural_language}
                >
                  {f.label}
                </span>
              </li>
            ))}
          </ul>
          <p className="text-xs text-zinc-500 mt-2">
            (Custom views ship in the next update — these are suggestions for
            now.)
          </p>
        </section>
      )}

      <section className="space-y-6">
        {view.groupings.map((g, i) => (
          <Group
            key={i}
            label={g.label}
            summary={g.summary}
            entryIds={g.entry_ids}
            bodies={bodies}
            entriesById={entriesById}
            onReply={onReply}
            slug={slug}
          />
        ))}
      </section>

      <p className="text-xs text-zinc-400 text-right">
        Generated by AI · {cached ? "cached" : "fresh"} ·{" "}
        {timeAgo(generatedAt)}
        {costUsd > 0 ? ` · $${costUsd.toFixed(4)}` : ""}
      </p>
    </div>
  );
}

// ---------- Group ----------

function Group({
  label,
  summary,
  entryIds,
  bodies,
  entriesById,
  onReply,
  slug,
}: {
  label: string;
  summary: string | null;
  entryIds: string[];
  bodies: Record<string, EntryWithBody>;
  entriesById: Record<string, ChainEntry>;
  onReply: (e: ChainEntry) => void;
  slug: string;
}) {
  return (
    <div>
      <h2 className="text-base font-semibold tracking-tight text-zinc-900 mb-1">
        {label}
      </h2>
      {summary && (
        <p className="text-sm text-zinc-600 mb-3 leading-relaxed">{summary}</p>
      )}
      <div className="space-y-3">
        {entryIds.map((id) => {
          const entry = entriesById[id];
          const body = bodies[id];
          if (!entry) return null;
          return (
            <EntryRef
              key={id}
              entry={entry}
              body={body ?? null}
              onReply={onReply}
              slug={slug}
            />
          );
        })}
      </div>
    </div>
  );
}

// ---------- Callout ----------

function Callout({
  tone,
  text,
  relatedEntryIds,
}: {
  tone: "neutral" | "warning" | "info";
  text: string;
  relatedEntryIds: string[];
}) {
  const styles =
    tone === "warning"
      ? "border-amber-300 bg-amber-50 text-amber-900"
      : tone === "info"
        ? "border-sky-200 bg-sky-50 text-sky-900"
        : "border-zinc-200 bg-zinc-50 text-zinc-800";
  return (
    <div className={`rounded-lg border px-4 py-3 text-sm ${styles}`}>
      <p>{text}</p>
      {relatedEntryIds.length > 0 && (
        <p className="text-xs opacity-70 mt-1">
          Related:{" "}
          {relatedEntryIds.slice(0, 5).map((id, i) => (
            <span key={id}>
              {i > 0 && ", "}
              <a
                href={`#e-${id}`}
                className="font-mono no-underline hover:underline"
              >
                {id.slice(0, 8)}
              </a>
            </span>
          ))}
        </p>
      )}
    </div>
  );
}

// ---------- EntryRef ----------
// Compact entry rendering inside the AI view groupings. Links to the full
// entry anchor (which the chronological view also uses) so cross-view linking
// works.

function EntryRef({
  entry,
  body,
  onReply,
}: {
  entry: ChainEntry;
  body: EntryWithBody | null;
  onReply: (e: ChainEntry) => void;
  slug: string;
}) {
  const [open, setOpen] = useState(false);
  const erased = body?.erased ?? false;
  const text = body?.body ?? null;
  const preview =
    text && !erased
      ? text.replace(/\s+/g, " ").slice(0, 160) +
        (text.length > 160 ? "…" : "")
      : null;

  return (
    <article
      id={`e-${entry.id}`}
      className="rounded-md border border-zinc-200 bg-white p-3"
    >
      <header className="flex items-center justify-between text-xs text-zinc-500">
        <div className="flex items-center gap-2">
          <span className="font-mono">#{entry.seq}</span>
          {entry.kind === "moderation" && (
            <span className="rounded-full bg-amber-100 text-amber-900 px-2 py-0.5 text-[10px] uppercase tracking-wide">
              Moderator
            </span>
          )}
          {entry.parent && (
            <span className="text-zinc-400">↳ reply</span>
          )}
        </div>
        <button
          type="button"
          onClick={() => onReply(entry)}
          className="text-zinc-500 hover:text-zinc-900"
        >
          Reply
        </button>
      </header>

      {erased ? (
        <p className="mt-2 text-sm italic text-zinc-500">[body erased]</p>
      ) : (
        <div className="mt-2">
          {open && text ? (
            <div className="prose-entry text-sm">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                disallowedElements={["script", "iframe", "style", "img"]}
                unwrapDisallowed
              >
                {text}
              </ReactMarkdown>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="mt-2 text-xs text-zinc-500 hover:text-zinc-900"
              >
                Show less
              </button>
            </div>
          ) : (
            <button
              type="button"
              onClick={() => setOpen(true)}
              className="text-left text-sm text-zinc-700 hover:text-zinc-900"
            >
              {preview ?? "[loading…]"}
            </button>
          )}
        </div>
      )}
    </article>
  );
}

function timeAgo(iso: string): string {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return iso;
  const seconds = Math.floor((Date.now() - then) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return new Date(iso).toLocaleDateString();
}
